title: OK Delivery Docs
description: Примеры техдоков (API, Release Notes, User Guides)
theme: minima
plugins:
  - jekyll-seo-tag
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
favicon: /assets/favicon.ico
